### ISSUE TITLE
Broken screenshots in extension description within VSCode itself

### ISSUE THREAD

**Issue by DervishD** [microsoft/vscode-hexeditor#216] opened 2021-03-04 16:37 UTC
When the extension is selected on the extension browser within Visual Studio Code itself (tested on version 1.53.2), the images corresponding to the screenshots of navigating and editing a file, the first two ones on the description at the time of this writing, appear as broken links.

Tested on Visual Code Studio for Windows x64, version 1.53.2 on Windows 10 20H2.

I'm including a partial screenshot showing the problem within the editor.

Thanks a lot in advance and feel free to contact me if you need more information.

![screenshot](https://user-images.githubusercontent.com/12148736/109997189-3c53b680-7d10-11eb-891f-af2ff1f37765.png)

**Comment by lramos15** [comment] 2021-03-08 19:10
Thanks for reporting, I believe this is caused by me removing them from the extension in an attempt to reduce the bundle size.

**Comment by DervishD** [comment] 2021-03-08 19:24
No big deal, Logan, it doesn't affect the extension functionality, it just looks untidy.

The extension is great 👍🏼

**Comment by lramos15** [comment] 2021-03-10 14:18
Should be fixed on next release by https://github.com/microsoft/vscode-hexeditor/commit/7f7e93bef8e3f4817f6fc305a0daafd26251cac6

**Closed by lramos15** 2021-03-10 14:18 UTC
