### ISSUE TITLE
Unable to install 'ms-vscode.hexeditor' extension because it is not compatible with the current version of VS Code (version 1.42.1)

### ISSUE THREAD

**Issue by storenth** [microsoft/vscode-hexeditor#176] opened 2020-08-19 05:11 UTC
OS: macOs Catalina 10.15.6 (19G73)
VS Code version:
```
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.6.0
```
<img width="1552" alt="Снимок экрана 2020-08-19 в 12 16 18" src="https://user-images.githubusercontent.com/18244131/90594991-0177ae80-e216-11ea-8d3e-e4aedb0186c4.png">
<img width="1552" alt="Снимок экрана 2020-08-19 в 12 13 46" src="https://user-images.githubusercontent.com/18244131/90595004-089ebc80-e216-11ea-85d5-af242eb8f4f8.png">
<img width="1552" alt="Снимок экрана 2020-08-19 в 12 14 56" src="https://user-images.githubusercontent.com/18244131/90595001-076d8f80-e216-11ea-9d39-7d7feb78fd26.png">

```
[2020-08-19 12:06:13.488] [exthost] [info] extension host started
[2020-08-19 12:06:13.588] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2020-08-19 12:06:13.588] [exthost] [info] ExtensionService#loadCommonJSModule file:///private/var/folders/rw/v__l1r2s31751mbhf042y13c0000gn/T/AppTranslocation/3100F54A-B043-4DF8-983D-825DE65B8D5C/d/Visual Studio Code.app/Contents/Resources/app/extensions/debug-auto-launch/dist/extension
[2020-08-19 12:06:13.594] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"*"}
[2020-08-19 12:06:13.595] [exthost] [info] ExtensionService#loadCommonJSModule file:///private/var/folders/rw/v__l1r2s31751mbhf042y13c0000gn/T/AppTranslocation/3100F54A-B043-4DF8-983D-825DE65B8D5C/d/Visual Studio Code.app/Contents/Resources/app/extensions/emmet/dist/extension
[2020-08-19 12:06:13.619] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.git","_lower":"vscode.git"},"activationEvent":"*"}
[2020-08-19 12:06:13.619] [exthost] [info] ExtensionService#loadCommonJSModule file:///private/var/folders/rw/v__l1r2s31751mbhf042y13c0000gn/T/AppTranslocation/3100F54A-B043-4DF8-983D-825DE65B8D5C/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/main
[2020-08-19 12:06:13.671] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"*"}
[2020-08-19 12:06:13.671] [exthost] [info] ExtensionService#loadCommonJSModule file:///private/var/folders/rw/v__l1r2s31751mbhf042y13c0000gn/T/AppTranslocation/3100F54A-B043-4DF8-983D-825DE65B8D5C/d/Visual Studio Code.app/Contents/Resources/app/extensions/merge-conflict/dist/extension
[2020-08-19 12:06:13.677] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
[2020-08-19 12:06:13.677] [exthost] [info] ExtensionService#loadCommonJSModule file:///private/var/folders/rw/v__l1r2s31751mbhf042y13c0000gn/T/AppTranslocation/3100F54A-B043-4DF8-983D-825DE65B8D5C/d/Visual Studio Code.app/Contents/Resources/app/extensions/search-result/dist/extension.js
[2020-08-19 12:06:13.681] [exthost] [info] ExtensionService#_doActivateExtension vscode.vscode-account {"startup":true,"extensionId":{"value":"vscode.vscode-account","_lower":"vscode.vscode-account"},"activationEvent":"*"}
[2020-08-19 12:06:13.681] [exthost] [info] ExtensionService#loadCommonJSModule file:///private/var/folders/rw/v__l1r2s31751mbhf042y13c0000gn/T/AppTranslocation/3100F54A-B043-4DF8-983D-825DE65B8D5C/d/Visual Studio Code.app/Contents/Resources/app/extensions/vscode-account/dist/extension.js
[2020-08-19 12:06:13.686] [exthost] [info] ExtensionService#_doActivateExtension dbaeumer.vscode-eslint {"startup":true,"extensionId":{"value":"dbaeumer.vscode-eslint","_lower":"dbaeumer.vscode-eslint"},"activationEvent":"*"}
[2020-08-19 12:06:13.686] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/storenth/.vscode/extensions/dbaeumer.vscode-eslint-2.1.1/client/out/extension
[2020-08-19 12:06:13.705] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens {"startup":true,"extensionId":{"value":"eamodio.gitlens","_lower":"eamodio.gitlens"},"activationEvent":"*"}
[2020-08-19 12:06:13.705] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/storenth/.vscode/extensions/eamodio.gitlens-10.2.2/dist/extension
[2020-08-19 12:06:13.731] [exthost] [info] ExtensionService#_doActivateExtension monokai.theme-monokai-pro-vscode {"startup":true,"extensionId":{"value":"monokai.theme-monokai-pro-vscode","_lower":"monokai.theme-monokai-pro-vscode"},"activationEvent":"*"}
[2020-08-19 12:06:13.731] [exthost] [info] ExtensionService#loadCommonJSModule file:///Users/storenth/.vscode/extensions/monokai.theme-monokai-pro-vscode-1.1.17/js/main
[2020-08-19 12:06:14.077] [exthost] [info] eager extensions activated
[2020-08-19 12:06:23.251] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"extensionId":{"value":"vscode.configuration-editing","_lower":"vscode.configuration-editing"},"activationEvent":"onLanguage:json"}
[2020-08-19 12:06:23.251] [exthost] [info] ExtensionService#loadCommonJSModule file:///private/var/folders/rw/v__l1r2s31751mbhf042y13c0000gn/T/AppTranslocation/3100F54A-B043-4DF8-983D-825DE65B8D5C/d/Visual Studio Code.app/Contents/Resources/app/extensions/configuration-editing/dist/extension
[2020-08-19 12:06:23.256] [exthost] [info] ExtensionService#_doActivateExtension vscode.extension-editing {"startup":false,"extensionId":{"value":"vscode.extension-editing","_lower":"vscode.extension-editing"},"activationEvent":"onLanguage:json"}
[2020-08-19 12:06:23.256] [exthost] [info] ExtensionService#loadCommonJSModule file:///private/var/folders/rw/v__l1r2s31751mbhf042y13c0000gn/T/AppTranslocation/3100F54A-B043-4DF8-983D-825DE65B8D5C/d/Visual Studio Code.app/Contents/Resources/app/extensions/extension-editing/dist/extension
[2020-08-19 12:06:23.269] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"extensionId":{"value":"vscode.json-language-features","_lower":"vscode.json-language-features"},"activationEvent":"onLanguage:json"}
[2020-08-19 12:06:23.269] [exthost] [info] ExtensionService#loadCommonJSModule file:///private/var/folders/rw/v__l1r2s31751mbhf042y13c0000gn/T/AppTranslocation/3100F54A-B043-4DF8-983D-825DE65B8D5C/d/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/client/dist/jsonMain
[2020-08-19 12:06:23.297] [exthost] [info] ExtensionService#_doActivateExtension vscode.npm {"startup":false,"extensionId":{"value":"vscode.npm","_lower":"vscode.npm"},"activationEvent":"onLanguage:json"}
[2020-08-19 12:06:23.297] [exthost] [info] ExtensionService#loadCommonJSModule file:///private/var/folders/rw/v__l1r2s31751mbhf042y13c0000gn/T/AppTranslocation/3100F54A-B043-4DF8-983D-825DE65B8D5C/d/Visual Studio Code.app/Contents/Resources/app/extensions/npm/dist/main
[2020-08-19 12:15:44.800] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"extensionId":{"value":"vscode.typescript-language-features","_lower":"vscode.typescript-language-features"},"activationEvent":"onLanguage:jsonc"}
[2020-08-19 12:15:44.800] [exthost] [info] ExtensionService#loadCommonJSModule file:///private/var/folders/rw/v__l1r2s31751mbhf042y13c0000gn/T/AppTranslocation/3100F54A-B043-4DF8-983D-825DE65B8D5C/d/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/dist/extension
```

**Comment by storenth** [comment] 2020-08-19 06:01
Root cause https://github.com/Microsoft/vscode/issues/7426 unable to update the VS Code

**Comment by lramos15** [comment] 2020-08-20 03:46
Have you tried the solutions outlined in that root cause issue? This isn't a problem with this extension as the extension clearly states you must have VS Code 1.46.0 or greater.

**Comment by mjbvz** [comment] 2020-09-08 23:18
Closing as expected. This extension requires VS Code 1.46+

**Closed by mjbvz** 2020-09-08 23:18 UTC
