### ISSUE TITLE
Enter should find next in search

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#145] opened 2020-07-24 17:15 UTC
Testing microsoft/vscode#103174

It seems to start a new search, to align with how find works in other areas it should find the next from the currently focused cell.

![recording (14)](https://user-images.githubusercontent.com/2193314/88417298-8fd34e80-cd96-11ea-97fe-dd2ca4c15446.gif)

**Comment by lramos15** [comment] 2020-07-24 17:16
Duplicate of https://github.com/microsoft/vscode-hexeditor/issues/105 and Fixed :)

**Closed by lramos15** 2020-07-24 17:16 UTC
