### ISSUE TITLE
Visual Glitches

### ISSUE THREAD

**Issue by ali90taz** [microsoft/vscode-hexeditor#181] opened 2020-08-29 02:28 UTC
**I'm discovery today this extension, i'm loved!
Unfortunately got visual glitch after resize vs code, any steps for fix?**

Visual Studio Code Version:

Version: 1.48.2 (user setup)
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:13:11.295Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Extension Version: 

v1.21

[https://drive.google.com/file/d/1lW_yKQhi73XvLg1-j2DSi3I-NV6lCzlX/view?usp=sharing](https://drive.google.com/file/d/1lW_yKQhi73XvLg1-j2DSi3I-NV6lCzlX/view?usp=sharing)

**Comment by mjbvz** [comment] 2020-10-16 19:31
Duplicate of #190

**Closed by mjbvz** 2020-10-16 19:31 UTC
Labels: help wanted
