### ISSUE TITLE
Page up/down should move the "cursor"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-hexeditor#102] opened 2020-07-23 17:19 UTC
Testing https://github.com/microsoft/vscode/issues/103176

- Focus something
- Press page up/down
- It should move the cursor down by a page, instead it just scrolls and then I can't move the cursor

**Comment by lramos15** [comment] 2020-07-23 17:22
Duplicate of #22

**Closed by lramos15** 2020-07-23 17:22 UTC
