### ISSUE TITLE
Compare  Hex Files

### ISSUE THREAD

**Issue by MathiasClarity** [microsoft/vscode-hexeditor#445] opened 2023-07-03 07:41 UTC
Thank you for this good extension, but unfortunately one important thing is missing, the comparison of the binary files. I tried several times, but the differences of the HEX files are not shown in .

It would be great if that would work, because the amount of data is very large and it is very difficult for people to visually recognize differences.

Best regards,
Mathias Weichert

HEX Files not working:
![grafik](https://github.com/microsoft/vscode-hexeditor/assets/101187323/0eb86e1a-1997-41a2-8593-18a178d1f0a4)

ASCII  Files works fine:

![grafik](https://github.com/microsoft/vscode-hexeditor/assets/101187323/7b529374-7448-4fba-8ae3-478526ab8714)

**Comment by lramos15** [comment] 2023-07-05 13:49
Duplicate of #47

**Closed by lramos15** 2023-07-05 13:49 UTC
