### ISSUE TITLE
Feature request: Enable file comparison

### ISSUE THREAD

**Issue by otoshi1205** [microsoft/vscode-hexeditor#73] opened 2020-07-08 09:25 UTC
It would be great to have the possibility to compare hexdumps. Right now, after clicking F1->"File: Compare active file with..." and selecting a file to compare, the selected file is being open instead of comparison view.

Keep up the good work guys. :)

**Comment by lramos15** [comment] 2020-07-08 13:41
Duplicate of #47

**Closed by lramos15** 2020-07-08 13:41 UTC
