### ISSUE TITLE
Gifs in the readme/ext detail are broken

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#220] opened 2021-03-13 21:33 UTC
<img width="462" alt="Screen Shot 2021-03-13 at 1 32 34 PM" src="https://user-images.githubusercontent.com/2193314/111045004-9fc0a100-8400-11eb-83cb-545476b06b6f.png">
<img width="544" alt="Screen Shot 2021-03-13 at 1 33 06 PM" src="https://user-images.githubusercontent.com/2193314/111045018-ab13cc80-8400-11eb-901b-375c6207f2dd.png">

**Comment by lramos15** [comment] 2021-03-15 13:52
Duplicate of https://github.com/microsoft/vscode-hexeditor/issues/216. Fixed by using static gif URLs.

**Closed by lramos15** 2021-03-15 13:52 UTC
Labels: duplicate
