### ISSUE TITLE
In the "Data Inspector" pane, show the address/offset of the currently-selected byte

### ISSUE THREAD

**Issue by DeflateAwning** [microsoft/vscode-hexeditor#517] opened 2024-04-27 05:34 UTC
When you click on a byte, it would be nice if it showed the address/offset of that byte (in hex and dec) in the file, alongside all the value representations of that byte.

**Comment by jogo-** [comment] 2024-04-27 15:58
Duplicate of #424 
Done in #486

**Comment by DeflateAwning** [comment] 2024-04-27 16:03
Screenshot?

**Comment by jogo-** [comment] 2024-04-27 16:25
Sure! Hex Editor v1.9.14
![image](https://github.com/microsoft/vscode-hexeditor/assets/4701169/6b18146b-ead4-44f7-a8ce-8efe269348a7)

**Closed** 2024-04-27 17:17 UTC
