### ISSUE TITLE
Bug: Extension Name

### ISSUE THREAD

**Issue by Malix-off** [microsoft/vscode-hexeditor#487] opened 2024-02-10 17:15 UTC
https://marketplace.visualstudio.com/items?itemName=ms-vscode.hexeditor
description == "`%description`"
![image](https://github.com/microsoft/vscode-hexeditor/assets/76160668/dba09de8-5a22-4414-8114-7bb1a0107c0b)

**Comment by connor4312** [comment] 2024-02-10 19:11
Dupe of https://github.com/microsoft/vscode-hexeditor/issues/484

**Closed by connor4312** 2024-02-10 19:11 UTC
