### ISSUE TITLE
Support multi-cell selection

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#26] opened 2020-06-08 18:22 UTC
Currently only a single cell can be selected and trying to drag show an overlay that looks like it's dragging the whole document like an image:

![image](https://user-images.githubusercontent.com/2193314/84066083-42338b80-a97a-11ea-96ad-71a09ae9f8a7.png)

**Comment by lramos15** [comment] 2020-06-08 18:46
Duplicate of #7

**Closed by lramos15** 2020-06-08 18:46 UTC
