### ISSUE TITLE
can't open image

### ISSUE THREAD

**Issue by mhamri** [microsoft/vscode-hexeditor#193] opened 2020-10-14 04:08 UTC
i'm trying to open a png file with hex editor but it doesn't work. no message. no error

btw the readme.md is outdated. none of these three is available 

> 
> Trigger the command palette (Ctrl / Cmd + Shift + P) -> Reopen With -> Hex Editor
> Right click a file -> Open With -> Hex Editor
> Trigger the command palette (Ctrl / Cmd + Shift + P) -> Open File using Hex Editor

**Comment by mjbvz** [comment] 2020-10-14 07:32
Are you sure the extension is installed and enabled?

**Comment by mhamri** [comment] 2020-10-15 06:33
yes, I open a png then I try to invoke the command which is "hex editor:open file" (this is the only hex editor command I have available
![image](https://user-images.githubusercontent.com/8991783/96085304-355c1100-0ef3-11eb-837b-9b2c6448ea78.png)

if I run this on normal files, I can see it open the file with hex editor. 
but when I have a png open it doesn't do anything 

just a note. the png isn't inside the workspace if it makes any difference!?

**Comment by mjbvz** [comment] 2020-10-16 19:29
What about `reopen with`? See #59 for why the `hexeditor` command is not available

**Comment by mhamri** [comment] 2020-10-27 17:17
`view: reopen with` works. thanks

**Comment by mjbvz** [comment] 2020-10-27 19:15
Duplicate of  #59

**Closed by mjbvz** 2020-10-27 19:15 UTC
