### ISSUE TITLE
Cell focus border color uses a bad default

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-hexeditor#141] opened 2020-07-24 16:35 UTC
Testing https://github.com/microsoft/vscode/issues/103174

On Topaz (Dim):

![image](https://user-images.githubusercontent.com/2193314/88413910-e5a4f800-cd90-11ea-890f-e8388cd88ae6.png)

Why doesn't it use the standard focus border to fix with everything?

![image](https://user-images.githubusercontent.com/2193314/88413949-f0f82380-cd90-11ea-959e-d6ef90a6fe41.png)

**Comment by lramos15** [comment] 2020-07-24 17:22
![recording](https://user-images.githubusercontent.com/4544166/88417843-abe3e980-cdb0-11ea-910b-77039e88850d.gif)
I don't see any focus problems

**Comment by Tyriar** [comment] 2020-07-24 17:30
:focus is using status bar background color which is black unless debugging (in which case it's yellow):

![image](https://user-images.githubusercontent.com/2193314/88418589-a24e8780-cd98-11ea-83ff-54aca10bdb76.png)

It should be using `focusBorder`

**Comment by lramos15** [comment] 2020-07-24 17:32
Duplicate of #104  Fixed by https://github.com/microsoft/vscode-hexeditor/commit/702eec4f68fd7d62aff6c5640a730cb5673d4b2f

**Closed by lramos15** 2020-07-24 17:32 UTC
