### ISSUE TITLE
Incorrect data content displayed at 000FFFF0

### ISSUE THREAD

**Issue by BigBro2014** [microsoft/vscode-hexeditor#360] opened 2022-06-15 05:45 UTC
Issue Type: <b>Bug</b>

Fill a binary file of 1024 * 1024 bytes with 0x00~0xFF by secquence, then open file us Hex Editor, incorrect data content 00..00 will be displayed at 000FFFF0. File test.bin attached in zip file.

Extension version: 1.9.6
VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.41GB (3.10GB free)|
|Process Argv|E:\\TEST.BIN --crash-reporter-id f6adc957-40c0-446c-8bf3-108bbb24a67a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

<!-- generated by issue reporter --
[TEST.zip](https://github.com/microsoft/vscode-hexeditor/files/8905981/TEST.zip)
>

**Comment by lramos15** [comment] 2022-06-15 12:26
Sounds like a duplicate of https://github.com/microsoft/vscode-hexeditor/issues/358 still need to ship a new version but this has been fixed

**Closed** 2022-06-15 12:26 UTC
