### ISSUE TITLE
Decoded text shifted, when 0x2D symbol is in file

### ISSUE THREAD

**Issue by DeyMass** [microsoft/vscode-hexeditor#284] opened 2021-04-26 03:59 UTC
1. Empty scratch file
2. Put some 0x00 (i used 48 bytes)
3. Replace three bytes somewhere in the middle for 0x32, 0x2D, 0x32
4. Decoded text is shifted down like '\n' in printf, but end of row after thoose 3 bytes is printed over the next line

When first 0x32 byte is removed, the decoded string representation becomes normal

Extension version: 1.5.0
VS Code version: Code 1.55.2 (3c4e3df9e89829dce27b7b5c24508306b151f30d, 2021-04-13T09:37:02.931Z)
OS version: Linux x64 4.15.0-141-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz (4 x 2660)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|7.66GB (0.23GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id 9821590b-93fc-4d51-a43b-de532fb4b776|
|Screen Reader|no|
|VM|22%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt678:30270856
pythonvspyt602cf:30291500
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30291489
pythontb:30283811
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30276952
pythondataviewer:30285071
vscus158:30286553


```

</details>

![screenshot](https://user-images.githubusercontent.com/17542966/116027100-2e6e4200-a67e-11eb-8cdb-20e229611cca.png)

**Comment by lramos15** [comment] 2021-04-26 14:32
<img width="811" alt="Screen Shot 2021-04-26 at 10 30 40 AM" src="https://user-images.githubusercontent.com/4544166/116099978-7db27380-a67a-11eb-8a89-e4981fcefc71.png">
I have a feeling this is a duplicate of https://github.com/microsoft/vscode-hexeditor/issues/214

**Closed by lramos15** 2021-04-26 14:32 UTC
